DELETE FROM DeckCards
DELETE FROM DiscardPileCards
DELETE FROM HandCards
DELETE FROM ScorePileCards

DELETE FROM Decks
DELETE FROM DiscardPiles
DELETE FROM Hands
DELETE FROM ScorePiles

DELETE FROM Participants
DELETE FROM Games