DELETE FROM DeckCard
DELETE FROM DiscardPileCard
DELETE FROM HandCard
DELETE FROM ScorePileCard

DELETE FROM Deck
DELETE FROM DiscardPile
DELETE FROM Hand
DELETE FROM ScorePile

DELETE FROM GameMember
DELETE FROM Game